version: '3.7'
services:
  oauth:
    depends_on:
      - database
    build:
      context: ./oauth
    volumes:
      - ./oauth:/home/gradle/src
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/gridwars
    ports:
      - 8080:8080
#      - 5005:5005

  frontend:
    build:
      context: ./ui
    ports:
      - 8081:8080
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  gridwars:
    depends_on:
      - oauth
      - frontend
    build:
      context: ./server
    environment:
      - OAUTH_HOST_NAME=oauth
    ports:
      - 8090:8090
#      - 5005:5005
    volumes:
      - ./server:/home/gradle/gridwars

  database:
    build:
      context: ./localdb
#    restart: always
    ports:
     # Try to remove the port and see if the server still able to connect
      - 5432:5432

  adminer:
    image: adminer
#    restart: always
    ports:
      - 9000:8080